### ISSUE TITLE
Empty-queue message is misleading during DJ Random's session

### ISSUE THREAD

**Issue by equin0x80** [arabek/demovibes#34]
When the queue is empty, the Pending Queue List displays this text: "There is no queue at the moment. DJ Random has the floor until new song requests are made!"

This is misleading during DJ Random's hour, because it looks like you could make a request, but actually they are blocked. For that period only, I would suggest replacing it with something like: "DJ Random has the floor! Requesting songs is temporarily disallowed."

(The message needs to make it clear that the block on requests is a deliberate decision and not a temporary fault or something. Even better, if possible, display the user's local time at which DJ Random's session will end.)

**Comment by penamety** [comment]
An attempt was made to change it in 5d6fb6372fa50a1b7147e3f100538fa527b962b1. The correct file is changed (and not the one at templates/global/webview/js/queue.html ) so provided the change was pulled in I don't know why it doesn't work. It only required a page refresh here.
Message could indeed be clarified a little even if still static (e.g. "DJ Random has the floor this hour!").

**Comment by arabek** [comment]
I've yet to update a local template on Nectarine. Not a bug.
